version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  citus_coordinator:
    container_name: citus_coordinator
    image: citusdata/citus:11.2
    ports:
      - "5433:5432"  # Expose the coordinator on port 5433
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
    volumes:
      - citus_coordinator_data:/var/lib/postgresql/data

  worker_1:
    container_name: worker_1
    image: citusdata/citus:11.2
    ports:
      - "5434:5432"  # Expose worker 1 on port 5434
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
    volumes:
      - worker_1_data:/var/lib/postgresql/data

  worker_2:
    container_name: worker_2
    image: citusdata/citus:11.2
    ports:
      - "5435:5432"  # Expose worker 2 on port 5435
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
    volumes:
      - worker_2_data:/var/lib/postgresql/data

volumes:
  db_data:
  citus_coordinator_data:
  worker_1_data:
  worker_2_data:
